"use client";

import Link from "next/link";
import { useLanguage } from "@/components/language-provider";
import { instinctInviteUrl } from "@/lib/public-integration-links";
import { CopyBlock } from "./guide-shell";
import { mcpEndpoint } from "./tool-reference";
import styles from "./guides.module.css";

export function McpClientSetup() {
  const { locale } = useLanguage();
  const es = locale === "es";
  const t = (en: string, spanish: string) => es ? spanish : en;
  return <div className={styles.clientSetup}>
    <p>{t("Choose where you want to use Magic Brain. Each remote client uses the same server URL above. For tools inside an open browser page, start with Instinct and the WebMCP guide.", "Elige dónde quieres usar Magic Brain. Todos los clientes remotos usan la misma URL de servidor indicada arriba. Para herramientas dentro de la página del navegador, empieza con Instinct y la guía WebMCP.")}</p>
    <div className={styles.notice}><strong>{t("Prefer an agent in your browser? We recommend Instinct.", "¿Prefieres un agente en el navegador? Recomendamos Instinct.")}</strong><p><a href={instinctInviteUrl}>{t("Join with Asier’s invitation", "Entrar con la invitación de Asier")} ↗</a>{" · "}<Link href="/webmcp#start">{t("Follow the WebMCP setup", "Seguir los pasos de WebMCP")}</Link></p></div>
    <details className={styles.expandable} id="setup-claude"><summary>Claude</summary>
      <ol><li>{t("Open Customize → Connectors and choose Add custom connector.", "Abre Customize → Connectors y elige Add custom connector.")}</li><li>{t("Name it Magic Brain and paste the full remote MCP URL above. Start without authentication for public research, or complete OAuth for personal tools.", "Llámalo Magic Brain y pega la URL MCP remota completa de arriba. Empieza sin autenticación para consultas públicas o completa OAuth para herramientas personales.")}</li><li>{t("In a conversation, use the + menu → Connectors to enable Magic Brain, then ask the first question below.", "En una conversación, usa el menú + → Connectors para activar Magic Brain y haz la primera pregunta de abajo.")}</li></ol>
      <p>{t("An organization administrator may need to enable custom connectors first.", "Un administrador puede tener que habilitar primero los conectores personalizados.")} <a href="https://claude.com/docs/connectors/custom/remote-mcp">{t("Claude’s setup guide", "Guía de Claude")} ↗</a></p>
    </details>
    <details className={styles.expandable} id="setup-chatgpt"><summary>ChatGPT</summary>
      <ol><li>{t("On ChatGPT web, open Settings → Security and login and turn on Developer mode.", "En ChatGPT web, abre Settings → Security and login y activa Developer mode.")}</li><li>{t("Open ChatGPT Plugins, select + and create a developer-mode app named Magic Brain with the remote MCP URL above.", "Abre ChatGPT Plugins, pulsa + y crea una app de Developer mode llamada Magic Brain con la URL MCP remota de arriba.")}</li><li>{t("Choose No Authentication for public-only research, or the supported OAuth/mixed authentication flow for personal access. Review the tools discovered by the app.", "Elige No Authentication para consultas públicas, o el flujo OAuth/autenticación mixta compatible para acceso personal. Revisa las herramientas que descubre la app.")}</li><li>{t("In the conversation’s + menu, choose Developer mode and select Magic Brain. Ask for a card’s Oracle text and rulings.", "En el menú + de la conversación, elige Developer mode y selecciona Magic Brain. Pide el texto Oracle y los rulings de una carta.")}</li></ol>
      <p>{t("OpenAI currently lists Pro, Plus, Business, Enterprise and Education accounts on the web. Workspace policies can still restrict access. Menu labels and availability may change.", "OpenAI incluye actualmente Pro, Plus, Business, Enterprise y Education en la web. Las políticas del espacio pueden restringir el acceso. Los menús y la disponibilidad pueden cambiar.")} <a href="https://developers.openai.com/api/docs/guides/developer-mode">{t("Official setup and availability", "Configuración y disponibilidad oficiales")} ↗</a></p>
    </details>
    <details className={styles.expandable} id="setup-grok"><summary>Grok</summary>
      <ol><li>{t("Open grok.com/connectors and select New Connector → Custom.", "Abre grok.com/connectors y selecciona New Connector → Custom.")}</li><li>{t("Paste the Magic Brain remote MCP URL above and complete any requested authentication. The hosted URL is already public; no local tunnel is needed.", "Pega la URL MCP remota de Magic Brain de arriba y completa la autenticación que se solicite. La URL alojada ya es pública; no necesitas un túnel local.")}</li><li>{t("Let Grok discover the tools, then ask it to use Magic Brain’s get_card_rules for Beorn the Fierce.", "Deja que Grok descubra las herramientas y pídele que use get_card_rules de Magic Brain para Beorn the Fierce.")}</li></ol>
      <p>{t("If Custom is not available in your account, check xAI’s current availability. Developers can also connect the endpoint through xAI’s remote MCP API.", "Si Custom no aparece en tu cuenta, revisa la disponibilidad actual de xAI. Los desarrolladores también pueden conectar el endpoint mediante la API MCP remota de xAI.")} <a href="https://docs.x.ai/grok/connectors">{t("Grok connector setup", "Configurar conectores de Grok")} ↗</a>{" · "}<a href="https://docs.x.ai/developers/tools/remote-mcp">{t("xAI API guide", "Guía de la API de xAI")} ↗</a></p>
    </details>
    <details className={styles.expandable} id="setup-gemini"><summary>Gemini · CLI</summary>
      <p>{t("This is the documented Gemini CLI route, not a setup for the Gemini web or mobile chat. If you have a supported Gemini CLI account, add the HTTP server with the command below.", "Esta es la vía documentada de Gemini CLI, no una configuración del chat web o móvil de Gemini. Si tienes acceso compatible con Gemini CLI, añade el servidor HTTP con este comando.")}</p>
      <CopyBlock label="Gemini CLI" text={`gemini mcp add --transport http magic-brain ${mcpEndpoint}`} />
      <p>{t("Start Gemini CLI and use /mcp to inspect the server. Ask it to use Magic Brain for a public card question. For personal tools, complete the CLI’s MCP OAuth flow when requested.", "Inicia Gemini CLI y usa /mcp para comprobar el servidor. Pide una consulta pública de cartas con Magic Brain. Para herramientas personales, completa el flujo OAuth de MCP de la CLI cuando se solicite.")}</p>
      <p>{t("Google’s June 2026 transition moves free and Google One CLI users to Antigravity CLI. Gemini CLI remains available through supported enterprise licenses or paid API keys. Follow the migration guide for your account; do not assume this command works in another product.", "La transición de Google de junio de 2026 mueve a los usuarios CLI gratuitos y Google One a Antigravity CLI. Gemini CLI sigue disponible con licencias empresariales compatibles o claves API de pago. Sigue la guía de migración de tu cuenta; no asumas que este comando sirve en otro producto.")}</p>
      <p><a href="https://geminicli.com/docs/tools/mcp-server/">{t("Gemini CLI MCP guide", "Guía MCP de Gemini CLI")} ↗</a>{" · "}<a href="https://developers.googleblog.com/an-important-update-transitioning-gemini-cli-to-antigravity-cli">{t("Google’s CLI transition guide", "Guía de transición de Google")} ↗</a></p>
    </details>
    <details className={styles.expandable} id="setup-codex"><summary>Codex</summary>
      <p>{t("Add this server table to ~/.codex/config.toml, preserving your other settings. A trusted project can use .codex/config.toml instead. Restart or refresh the client’s MCP connections after saving.", "Añade esta tabla a ~/.codex/config.toml conservando tus otros ajustes. Un proyecto de confianza puede usar .codex/config.toml. Reinicia o actualiza las conexiones MCP del cliente tras guardar.")}</p>
      <CopyBlock label="config.toml" text={`[mcp_servers.magic_brain]\nurl = "${mcpEndpoint}"`} />
      <p>{t("Start with public reads. For personal tools, run the OAuth login below and approve only the scopes you need. Use /mcp to inspect the connection in a supported Codex client.", "Empieza con consultas públicas. Para herramientas personales, inicia OAuth con el comando de abajo y aprueba solo los permisos necesarios. Usa /mcp para inspeccionar la conexión en un cliente Codex compatible.")}</p>
      <CopyBlock label={t("Optional personal access", "Acceso personal opcional")} text="codex mcp login magic_brain" />
      <p><a href="https://learn.chatgpt.com/docs/extend/mcp">{t("Official Codex MCP guide", "Guía oficial de MCP en Codex")} ↗</a></p>
    </details>
    <details className={styles.expandable} id="setup-cursor"><summary>Cursor</summary>
      <p>{t("Add this configuration to .cursor/mcp.json for a project, or ~/.cursor/mcp.json for your user. Merge it with any existing mcpServers entries. Enable or refresh Magic Brain in Cursor’s MCP tools and ask a question in Agent mode.", "Añade esta configuración a .cursor/mcp.json para un proyecto, o a ~/.cursor/mcp.json para tu usuario. Combínala con las entradas mcpServers existentes. Activa o actualiza Magic Brain en las herramientas MCP de Cursor y pregunta en modo Agent.")}</p>
      <CopyBlock label="mcp.json" text={JSON.stringify({ mcpServers: { "magic-brain": { url: mcpEndpoint } } }, null, 2)} />
      <p><a href="https://cursor.com/docs/mcp">{t("Cursor’s MCP guide", "Guía MCP de Cursor")} ↗</a></p>
    </details>
    <details className={styles.expandable} id="setup-vscode"><summary>VS Code + GitHub Copilot</summary>
      <p>{t("Run MCP: Add Server from the Command Palette, choose an HTTP server, paste the endpoint and name it magic-brain. Or merge the configuration below into .vscode/mcp.json. Start the server through MCP: List Servers, then enable its tools in Copilot Chat’s Agent mode. Organization policy may need to allow MCP.", "Ejecuta MCP: Add Server en la paleta de comandos, elige un servidor HTTP, pega el endpoint y llámalo magic-brain. También puedes añadir la configuración de abajo a .vscode/mcp.json. Inicia el servidor con MCP: List Servers y activa sus herramientas en modo Agent de Copilot Chat. Tu organización puede tener que autorizar MCP.")}</p>
      <CopyBlock label=".vscode/mcp.json" text={JSON.stringify({ servers: { "magic-brain": { type: "http", url: mcpEndpoint } } }, null, 2)} />
      <p><a href="https://code.visualstudio.com/docs/copilot/customization/mcp-servers">{t("VS Code’s MCP guide", "Guía MCP de VS Code")} ↗</a></p>
    </details>
    <details className={styles.expandable} id="setup-api-cli"><summary>{t("Your own app, API or command line", "Tu aplicación, API o terminal")}</summary>
      <p>{t("For a direct HTTP integration, start with the public card catalogue request below, then follow the Developer hub for endpoints, pagination and account scopes. API keys and MCP OAuth are separate authentication paths.", "Para integrar por HTTP, empieza con esta consulta al catálogo público y sigue la guía de Desarrolladores para endpoints, paginación y permisos. Las claves API y OAuth de MCP son vías de autenticación distintas.")}</p>
      <CopyBlock label="HTTP" text={'curl "https://magicbrain.es/api/v1/cards?q=lotus&limit=3"'} />
      <p>{t("The repository also includes a local CLI. Follow its README to build it, then run cards search. Use an MCP-capable API client if you want your own assistant to discover and call the hosted tools.", "El repositorio también incluye una CLI local. Sigue su README para compilarla y ejecuta cards search. Usa un cliente API compatible con MCP si quieres que tu propio asistente descubra y ejecute las herramientas alojadas.")}</p>
      <CopyBlock label="CLI" text="node tools/magic-brain-cli/dist/index.js cards search --query lotus --limit 3 --json" />
      <p><Link href="/developers#reference">{t("REST API reference", "Referencia REST API")}</Link>{" · "}<Link href="/developers#mcp">{t("OpenAI Responses API example", "Ejemplo de OpenAI Responses API")}</Link>{" · "}<a href="https://github.com/assarasua/magic-brain/tree/main/tools/magic-brain-cli">{t("CLI setup", "Instalación de la CLI")} ↗</a></p>
    </details>
    <CopyBlock label={t("Your first question", "Tu primera pregunta")} text={t("Use Magic Brain’s get_card_rules for Beorn the Fierce. Show the mana cost, complete Oracle text, card rulings and source dates.", "Usa get_card_rules de Magic Brain para Beorn the Fierce. Muestra el coste de maná, Oracle completo, rulings y fechas de las fuentes.")} />
  </div>;
}
