"use client";

import Link from "next/link";
import { useLanguage } from "@/components/language-provider";
import { CopyBlock, GuideSection, GuideShell } from "./guide-shell";
import { ToolCatalogue } from "./tool-catalogue";
import { McpClientSetup } from "./mcp-client-setup";
import { AssistantCompatibility } from "./compatibility";
import { mcpEndpoint, toolGuides } from "./tool-reference";
import styles from "./guides.module.css";

export function McpGuide() {
  const { locale } = useLanguage();
  const es = locale === "es";
  const t = (en: string, spanish: string) => es ? spanish : en;
  const sections = [
    ["connect", t("Connect your assistant", "Conecta tu asistente")],
    ["compatibility", t("Assistant compatibility", "Asistentes compatibles")],
    ["overview", t("What you can do", "Qué puedes hacer")],
    ["card-rules", t("Cards, effects & rules", "Cartas, efectos y reglas")],
    ["workflows", t("Example workflows", "Ejemplos de uso")],
    ["tools", t("All tools", "Todas las herramientas")],
    ["permissions", t("Accounts & permissions", "Cuentas y permisos")],
    ["evidence", t("Reading the evidence", "Cómo leer las evidencias")],
    ["privacy", t("Privacy & request context", "Privacidad y contexto")],
    ["troubleshooting", t("Troubleshooting", "Resolver problemas")],
    ["developers", t("For developers", "Para desarrolladores")],
  ] as const;
  return <GuideShell kind="mcp" title={t("Magic Brain, in your assistant.", "Magic Brain, en tu asistente.")} intro={t("Connect your AI assistant to Magic card data, Oracle text, rules, market research and your collection. This guide covers setup, every tool, and how to turn sourced evidence into useful answers.", "Conecta tu asistente de IA a datos de cartas, texto Oracle, reglas, mercado y tu colección. Esta guía explica la conexión, cada herramienta y cómo convertir evidencias documentadas en respuestas útiles.")} sections={[...sections]}>
    <GuideSection id="connect" title={t("Connect in a few steps", "Conecta en pocos pasos")}>
      <p>{t("Use a client that supports remote MCP over Streamable HTTP. A local stdio-only client cannot connect to this URL directly. Custom-server availability and organization policies depend on your client.", "Usa un cliente que admita MCP remoto mediante Streamable HTTP. Un cliente que solo admita stdio local no puede conectarse directamente a esta URL. La disponibilidad de servidores personalizados y las políticas de organización dependen del cliente.")}</p>
      <CopyBlock label={t("Remote MCP server URL · Streamable HTTP", "URL del servidor MCP remoto · Streamable HTTP")} text={mcpEndpoint} />
      <McpClientSetup />
      <h3>{t("The same connection flow in any MCP client", "El mismo flujo en cualquier cliente MCP")}</h3>
      <ol className={styles.steps}><li><strong>{t("Add a remote server.", "Añade un servidor remoto.")}</strong> {t("Open the client’s MCP, connectors or tools settings. Create a connection named Magic Brain and paste the full server URL above, including /mcp.", "Abre los ajustes de MCP, conectores o herramientas de tu cliente. Crea una conexión llamada Magic Brain y pega la URL completa, incluido /mcp.")}</li><li><strong>{t("Start with public access.", "Empieza con acceso público.")}</strong> {t("Card data, prices, effects, rules and product research work without a Magic Brain account or API key. If offered, choose anonymous/no authentication for this first check.", "Los datos de cartas, precios, efectos, reglas e investigación del producto funcionan sin cuenta ni clave API de Magic Brain. Si se ofrece, elige acceso anónimo para esta primera prueba.")}</li><li><strong>{t("Enable Magic Brain in the conversation.", "Activa Magic Brain en la conversación.")}</strong> {t("Some clients require you to enable a connector per conversation. Refresh the tool list and check that get_card_rules is available. The server currently advertises 32 tools; personal calls still require authorization.", "Algunos clientes exigen activar el conector en cada conversación. Actualiza la lista y comprueba que aparece get_card_rules. El servidor anuncia actualmente 32 herramientas; las llamadas personales siguen necesitando autorización.")}</li><li><strong>{t("Make a small first request.", "Haz una primera consulta sencilla.")}</strong> {t("Ask for Beorn the Fierce’s Oracle text and rulings using get_card_rules. A successful response includes mana cost, card faces and dated source evidence.", "Pide el texto Oracle y los rulings de Beorn the Fierce usando get_card_rules. La respuesta incluye maná, caras de la carta y fuentes fechadas.")}</li><li><strong>{t("Authorize your collection when needed.", "Autoriza tu colección cuando lo necesites.")}</strong> {t("For personal tools, follow the client’s OAuth sign-in flow, sign into Magic Brain, review the requested scopes, and approve only the access you want. Your website session alone does not authorize an external MCP client.", "Para herramientas personales, sigue el flujo OAuth del cliente, inicia sesión en Magic Brain, revisa los permisos y aprueba solo el acceso que quieras. La sesión de la web no autoriza por sí sola a un cliente MCP externo.")}</li></ol>
      <details className={styles.expandable}><summary>{t("Configuration files: common HTTP formats", "Archivos de configuración: formatos HTTP habituales")}</summary><p>{t("Use the format documented by your client. These are alternative configuration shapes, not files to combine. The endpoint is the same in both.", "Usa el formato documentado por tu cliente. Son formatos alternativos, no archivos que debas combinar. El endpoint es el mismo en ambos.")}</p><CopyBlock label="mcpServers / url" text={JSON.stringify({ mcpServers: { "magic-brain": { url: mcpEndpoint } } }, null, 2)} /><CopyBlock label="servers / type: http" text={JSON.stringify({ servers: { "magic-brain": { type: "http", url: mcpEndpoint } } }, null, 2)} /><p>{t("Keep API keys and OAuth tokens out of shared configuration files. A Magic Brain REST API key is not a substitute for the hosted connector’s OAuth login.", "No incluyas claves API ni tokens OAuth en archivos compartidos. Una clave REST de Magic Brain no sustituye al inicio de sesión OAuth del conector alojado.")}</p></details>
      <p><Link href="/developers#mcp">{t("Client-specific installation options in the Developer hub", "Opciones de instalación por cliente en Desarrolladores")} →</Link></p>
    </GuideSection>
    <GuideSection id="compatibility" title={t("Which assistants can connect?", "¿Qué asistentes se pueden conectar?")}><AssistantCompatibility /></GuideSection>
    <GuideSection id="overview" title={t("One connection. Cards, rules and collection tools.", "Una conexión. Cartas, reglas y colección.")}>
      <p>{t("MCP (Model Context Protocol) lets an assistant discover structured tools and call them with named inputs. Your assistant decides which tool to use, Magic Brain returns data and sources, and the assistant explains the result. Reading this page does not connect a client or run a tool.", "MCP (Model Context Protocol) permite a un asistente descubrir herramientas estructuradas y llamarlas con parámetros. Tu asistente elige la herramienta, Magic Brain devuelve datos y fuentes, y el asistente explica el resultado. Leer esta página no conecta un cliente ni ejecuta herramientas.")}</p>
      <div className={styles.stats}><div><strong>{toolGuides.length}</strong><span>{t("tools in the hosted MCP", "herramientas en el MCP alojado")}</span></div><div><strong>{toolGuides.filter(tool => !tool.scopes).length}</strong><span>{t("public research tools", "herramientas públicas")}</span></div><div><strong>OAuth</strong><span>{t("optional account access", "acceso opcional a tu cuenta")}</span></div></div>
      <div className={styles.routeCards}><a href="#card-rules"><strong>{t("A question during a game", "Una duda durante la partida")}</strong><span>{t("Get Oracle text, card rulings and numbered rules.", "Consulta Oracle, rulings y reglas numeradas.")}</span></a><a href="#workflows"><strong>{t("Research a card or collection", "Investiga una carta o colección")}</strong><span>{t("Find the exact printing and compare dated evidence.", "Encuentra la impresión y compara evidencias fechadas.")}</span></a></div>
      <p>{t("Want an agent to work inside an open Magic Brain browser tab? Read the ", "¿Quieres que un agente trabaje dentro de una pestaña de Magic Brain? Consulta la ")}<Link href="/webmcp">{t("WebMCP guide", "guía de WebMCP")}</Link>.</p>
    </GuideSection>
    <GuideSection id="card-rules" title={t("From a card name to an in-game explanation", "Del nombre de una carta a una explicación en partida")}>
      <p>{t("Printing details, Oracle text and the Comprehensive Rules are different sources. Choose the tool that answers the question you actually have.", "Los datos de una impresión, el texto Oracle y las Comprehensive Rules son fuentes distintas. Elige la herramienta que responde a tu pregunta.")}</p>
      <div className={styles.tableWrap}><table><thead><tr><th>{t("You need", "Necesitas")}</th><th>{t("Use", "Usa")}</th></tr></thead><tbody><tr><td>{t("Set, collector number, language, prices", "Edición, número, idioma, precios")}</td><td><code>search_cards → get_card</code></td></tr><tr><td>{t("Mana cost, Oracle text, faces, dated card rulings", "Maná, Oracle, caras, rulings fechados")}</td><td><code>get_card_rules</code></td></tr><tr><td>{t("Cards with a particular effect", "Cartas con un efecto concreto")}</td><td><code>search_card_effects</code></td></tr><tr><td>{t("How named cards interact in this game state", "Cómo interactúan cartas concretas en esta situación")}</td><td><code>explain_card_interaction</code></td></tr><tr><td>{t("A general rule or numbered section", "Una regla general o sección numerada")}</td><td><code>search_rules / ask_rules</code></td></tr></tbody></table></div>
      <h3>{t("Try Beorn the Fierce", "Prueba con Beorn the Fierce")}</h3>
      <CopyBlock label="get_card_rules" text={'{\n  "card": "Beorn the Fierce"\n}'} />
      <p>{t("In the snapshot checked on 19 September 2026, this resolves Beorn the Fierce (HOB #119), mana cost {3}{G}{G}, its complete Oracle text and a Wizards ruling dated 29 June 2026. That ruling explains that its triggered ability’s type-changing effect lasts indefinitely, including after cleanup or Beorn leaving the battlefield. Re-check returned source dates as the dataset changes.", "En la importación comprobada el 19 de septiembre de 2026, devuelve Beorn the Fierce (HOB #119), coste {3}{G}{G}, texto Oracle completo y un ruling de Wizards del 29 de junio de 2026. Ese ruling explica que el cambio de tipo de su habilidad disparada dura indefinidamente, incluso tras la limpieza o cuando Beorn deja el campo de batalla. Revisa las fechas devueltas cuando cambien los datos.")}</p>
      <p className={styles.notice}>{t("The official name has no comma: Beorn the Fierce. Catalogue search treats punctuation literally, and get_card_rules requires an exact name or ID. If uncertain, search a shorter name, inspect the returned identity and reuse its name or Oracle ID. A printing ID selects an edition; an Oracle ID identifies the game card across editions.", "El nombre oficial no lleva coma: Beorn the Fierce. La búsqueda del catálogo trata la puntuación literalmente y get_card_rules exige un nombre exacto o ID. Si hay dudas, busca un nombre más corto, comprueba la identidad y reutiliza el nombre o ID Oracle devuelto. El ID de impresión selecciona una edición; el ID Oracle identifica la carta entre ediciones.")}</p>
      <h3>{t("Give the interaction enough context", "Aporta contexto suficiente para la interacción")}</h3>
      <CopyBlock label="explain_card_interaction" text={JSON.stringify({ cards: ["Rest in Peace", "Blood Artist"], question: "Does Blood Artist trigger when another creature would die?", game_state: { active_player: "Player A", phase: "main phase", battlefield: ["Rest in Peace", "Blood Artist", "Another creature"], relevant_effects: ["The other creature would go from the battlefield to its graveyard."] } }, null, 2)} />
      <p>{t("Include the active player, phase, who has priority, relevant permanents, targets, choices and other effects. If the stack matters, list its objects in order and say which resolves next. State ownership/control and relevant timestamps in the descriptions. You can supply up to five exact card names or IDs. Ask the assistant to identify missing facts before drawing a conclusion.", "Incluye jugador activo, fase, quién tiene prioridad, permanentes relevantes, objetivos, elecciones y otros efectos. Si importa la pila, enumera sus objetos en orden e indica cuál se resuelve primero. Describe propietario/controlador y marcas de tiempo relevantes. Puedes aportar hasta cinco nombres exactos o IDs. Pide al asistente que identifique los datos ausentes antes de concluir.")}</p>
      <p>{t("For the example above, the relevant evidence includes rule 700.4 (dies) and 614.6 (a replaced event does not happen). The tool retrieves evidence; the host explains why a graveyard move replaced with exile does not create the death event Blood Artist is waiting for. Retrieved candidates are not all necessarily relevant, and the assistant must cite the rules that support its conclusion.", "En el ejemplo, las evidencias pertinentes incluyen la regla 700.4 (morir) y la 614.6 (un evento reemplazado no sucede). La herramienta recupera evidencias; el asistente explica por qué reemplazar el movimiento al cementerio por exilio no crea el evento de muerte que espera Blood Artist. No todas las reglas candidatas son necesariamente relevantes; el asistente debe citar las que fundamentan su conclusión.")}</p>
    </GuideSection>
    <GuideSection id="workflows" title={t("Requests you can give your assistant", "Peticiones para tu asistente")}>
      {[
        [t("Compare a printing’s value", "Compara el valor de una impresión"), t("Find Beorn the Fierce in HOB. Confirm the collector number and language, then compare its latest nonfoil and foil EUR observations. Include the source and observation date; leave missing prices unknown.", "Busca Beorn the Fierce en HOB. Confirma número de colección e idioma y compara sus últimas observaciones en EUR, normal y foil. Incluye fuente y fecha; deja los precios ausentes como desconocidos."), "search_cards → get_card → get_latest_prices / get_price_history"],
        [t("Discover effects for a deck", "Descubre efectos para un mazo"), t("Find cards with effects about drawing a card. Show five candidates, then get the full Oracle text for the two most relevant ones so we do not miss conditions or another face.", "Busca cartas con efectos de robar una carta. Muestra cinco candidatas y consulta el Oracle completo de las dos más relevantes para no omitir condiciones ni otra cara."), "search_card_effects → get_card_rules"],
        [t("Review your collection", "Revisa tu colección"), t("With my authorization, list my collection lists and summarize concentration in the one I choose. Show any model fallback or missing-price limitations. Do not change any holdings.", "Con mi autorización, enumera mis listas y resume la concentración de la que elija. Indica cualquier limitación del modelo o precio ausente. No cambies mis cartas."), "list_portfolio_lists → get_portfolio_list"],
        [t("Record a confirmed holding", "Registra una carta confirmada"), t("Find the exact printing I own. Show me the card, list, quantity, condition, language and recorded purchase price, then ask me to confirm before adding it.", "Encuentra la impresión exacta que tengo. Muéstrame carta, lista, cantidad, estado, idioma y precio de compra registrado, y pide mi confirmación antes de añadirla."), "search_cards → list_portfolio_lists → add_to_portfolio"],
      ].map(([title, prompt, flow]) => <article className={styles.workflow} key={title}><h3>{title}</h3><CopyBlock label={t("Example prompt", "Ejemplo de petición")} text={prompt} /><p className={styles.flow}>{flow}</p></article>)}
    </GuideSection>
    <GuideSection id="tools" title={t("The complete tool reference", "Referencia completa de herramientas")}>
      <p>{t("Every registered tool is listed below. Open a row for outputs, exact input limits, an argument example and the full input schema. Examples containing <...> need real IDs returned by earlier reads; they are not ready-to-run account actions. Tool and parameter names remain in English in both languages.", "A continuación aparecen todas las herramientas registradas. Abre una fila para ver resultados, límites, argumentos de ejemplo y el esquema completo. Los ejemplos con <...> necesitan IDs reales de consultas anteriores; no son acciones listas para ejecutar. Los nombres de herramientas y parámetros se mantienen en inglés.")}</p>
      <ToolCatalogue />
    </GuideSection>
    <GuideSection id="permissions" title={t("Your account, with explicit permissions", "Tu cuenta, con permisos explícitos")}>
      <p>{t("Public tools work anonymously. Five personal read tools and six account actions need OAuth and their exact scopes. Seeing a tool in tools/list does not mean you have permission to call it. The server checks the authorizing owner; passing somebody else’s list ID does not grant access.", "Las herramientas públicas funcionan de forma anónima. Cinco consultas personales y seis acciones requieren OAuth y sus permisos exactos. Ver una herramienta en tools/list no significa tener permiso para ejecutarla. El servidor comprueba al propietario autorizado; pasar el ID de otra persona no concede acceso.")}</p>
      <div className={styles.tableWrap}><table><thead><tr><th>{t("Scope", "Permiso")}</th><th>{t("What it allows here", "Qué permite aquí")}</th></tr></thead><tbody>{[
        ["profile:read", t("Preference-based research and profile context for portfolio analysis.", "Investigación según preferencias y contexto del perfil para analizar la colección.")],
        ["portfolio:read", t("Read owned holdings and their analysis.", "Consultar cartas propias y su análisis.")],
        ["lists:read", t("Read owned lists and their identities.", "Consultar listas propias y sus identidades.")],
        ["portfolio:write", t("Add holdings; required together with lists:write for removal.", "Añadir cartas; junto a lists:write, eliminarlas.")],
        ["lists:write", t("Create or rename lists; required for removing their holdings.", "Crear o renombrar listas; necesario para eliminar sus cartas.")],
        ["alerts:manage", t("Add, update or remove watchlist entries and price alerts.", "Añadir, actualizar o eliminar seguimiento y alertas.")],
      ].map(([scope, detail]) => <tr key={scope}><td><code>{scope}</code></td><td>{detail}</td></tr>)}</tbody></table></div>
      <h3>{t("Before an action changes data", "Antes de cambiar datos")}</h3><p>{t("The assistant must show the proposed action and get your explicit confirmation. Write tools require confirm: true as well as authorization. A true flag is a record of your decision, not permission for the assistant to assume it. Review the returned result before retrying; a new call may represent a new action. These tools do not buy or sell cards or transfer money.", "El asistente debe mostrar la acción propuesta y obtener tu confirmación expresa. Las herramientas de escritura exigen confirm: true además de autorización. Ese valor registra tu decisión; no permite que el asistente la suponga. Revisa el resultado antes de reintentar: una nueva llamada puede ser una nueva acción. Estas herramientas no compran ni venden cartas ni transfieren dinero.")}</p>
      <p>{t("OAuth uses authorization code with S256 PKCE and resource binding. Access tokens last 15 minutes; rotating refresh tokens last 30 days. Let the client manage tokens. If a scope is missing, reauthorize through the client and review the new consent request. Disconnect/revoke authorization through the controls supported by your client; revoking a REST API key is a separate operation.", "OAuth utiliza código de autorización con S256 PKCE y vinculación al recurso. Los tokens de acceso duran 15 minutos; los de renovación rotan y duran 30 días. Deja que el cliente los gestione. Si falta un permiso, vuelve a autorizar desde el cliente y revisa el consentimiento. Desconecta o revoca mediante los controles del cliente; revocar una clave REST es una operación distinta.")}</p>
    </GuideSection>
    <GuideSection id="evidence" title={t("Read the dates, sources and limitations", "Lee fechas, fuentes y limitaciones")}>
      <ul><li>{t("Prices: keep amount, currency, finish, source and observedAt together. A stored observation is not a live offer, volume measure or guarantee that you can sell at that price.", "Precios: conserva juntos importe, moneda, acabado, fuente y observedAt. Una observación guardada no es una oferta en directo, medida de volumen ni garantía de venta.")}</li><li>{t("Cards: an Oracle identity can have many printings. Confirm set, collector number, language and finish for market questions. get_card_rules is about game text, not printing value.", "Cartas: una identidad Oracle puede tener muchas impresiones. Confirma edición, número, idioma y acabado para consultas de mercado. get_card_rules trata el texto de juego, no el valor de una impresión.")}</li><li>{t("Rules: Oracle/rulings and the Comprehensive Rules are separate snapshots. Preserve their effective/retrieval dates, source URLs, rule numbers and PDF pages. A card with no imported rulings is not proof that no clarification exists anywhere.", "Reglas: Oracle/rulings y Comprehensive Rules son importaciones independientes. Conserva fechas, URLs, números de regla y páginas PDF. No tener rulings importados no demuestra que no exista ninguna aclaración.")}</li><li>{t("Game explanations: supplied game state is not verified. Ambiguous identities, unresolved timing or missing facts require clarification. The result is decision support, not an official judge ruling.", "Explicaciones de juego: el estado aportado no se verifica. Identidades ambiguas, tiempos sin resolver o datos ausentes requieren aclaración. El resultado es una ayuda, no una decisión oficial de juez.")}</li><li>{t("Forecasts and product research: preserve model/fallback status, assumptions and unknowns. A hypothesis or roadmap option must not be presented as a shipped feature, and a forecast is not a promised return.", "Previsiones e investigación del producto: conserva estado del modelo, supuestos y datos desconocidos. Una hipótesis u opción futura no es una función publicada, y una previsión no promete rentabilidad.")}</li></ul>
      <p>{t("Tools return text content and structuredContent. Public API tools generally wrap the API envelope under data and attach attribution; card-rules tools expose card/source or results/source directly. Follow each tool’s advertised outputSchema instead of assuming every tool has the same shape. A tool may report isError even when the HTTP request itself succeeded.", "Las herramientas devuelven texto y structuredContent. Las herramientas de API suelen envolver su respuesta en data y añadir attribution; las de reglas de cartas exponen card/source o results/source directamente. Sigue el outputSchema anunciado por cada herramienta. Puede existir isError aunque la petición HTTP haya tenido éxito.")}</p>
    </GuideSection>
    <GuideSection id="privacy" title={t("What accompanies a request", "Qué acompaña a una petición")}>
      <p>{t("Your AI client sends the selected tool and its arguments to Magic Brain. Personal results go back to that client, so use a client you trust with your collection. Magic Brain does not receive the original conversation automatically through MCP, but any text the client puts into a tool argument is sent to the service.", "Tu cliente envía la herramienta y sus argumentos a Magic Brain. Los resultados personales vuelven al cliente: usa uno al que confíes tu colección. MCP no envía automáticamente la conversación original a Magic Brain, pero cualquier texto incluido en un argumento sí llega al servicio.")}</p>
      <p>{t("Every tool accepts optional request_summary (1–500 characters) and request_context. If used, paraphrase only non-personal intent. Never copy the conversation, credentials, personal notes or identifiers into these audit fields. Omitting them is valid.", "Todas las herramientas admiten request_summary opcional (1–500 caracteres) y request_context. Si los usas, resume solo intención no personal. No copies conversaciones, credenciales, notas personales ni identificadores en estos campos de auditoría. Es válido omitirlos.")}</p>
      <CopyBlock label={t("Optional audit context", "Contexto de auditoría opcional")} text={JSON.stringify({ request_summary: "Research a card interaction", request_context: { intent: "rules", language: "en", output_format: "answer", subject: "Replacement effects and death triggers" } }, null, 2)} />
      <p>{t("Operational records can include tool name, success, timing, request ID, protocol, client user agent, origin, OAuth client/scopes, argument names and these optional context fields. Raw tool arguments and responses are excluded from the MCP audit event. The AI client has its own retention policy. See Magic Brain’s ", "Los registros operativos pueden incluir herramienta, éxito, duración, ID de petición, protocolo, cliente, origen, cliente/permisos OAuth, nombres de argumentos y contexto opcional. El evento de auditoría MCP excluye los argumentos y respuestas completos. El cliente de IA tiene su propia política de conservación. Consulta la ")}<Link href="/privacy">{t("privacy policy", "política de privacidad")}</Link>.</p>
    </GuideSection>
    <GuideSection id="troubleshooting" title={t("When something does not work", "Cuando algo no funciona")}>
      {[
        [t("I cannot see the new tools", "No aparecen las herramientas nuevas"), t("Refresh or reconnect the server and enable it for the current conversation. Verify the full /mcp URL and Streamable HTTP support. tools/list is the current contract; get_card_rules should be present. Organization settings can block custom servers.", "Actualiza o reconecta el servidor y actívalo en la conversación. Comprueba la URL /mcp completa y compatibilidad con Streamable HTTP. tools/list es el contrato actual; debe aparecer get_card_rules. La organización puede bloquear servidores personalizados.")],
        [t("The card is found but Oracle text is missing", "Encuentro la carta pero falta Oracle"), t("get_card returns catalogue and price data. Call get_card_rules with the exact returned name or Oracle ID. search_rules and ask_rules search the rulebook, not card-specific Oracle text.", "get_card devuelve catálogo y precios. Llama a get_card_rules con el nombre exacto o ID Oracle devuelto. search_rules y ask_rules buscan en el reglamento, no en el Oracle de la carta.")],
        [t("No match or ambiguous card (404 / 409)", "Carta no encontrada o ambigua (404 / 409)"), t("Check spelling, punctuation, the exact face name and identity. Shorten a catalogue query, then reuse its canonical result. For ambiguity, choose a returned candidate Oracle ID. Do not guess which card was intended.", "Comprueba ortografía, puntuación, nombre de cara e identidad. Acorta la consulta del catálogo y reutiliza el resultado canónico. Ante ambigüedad, elige un ID Oracle de los candidatos. No adivines la carta.")],
        [t("Personal calls fail (401 / 403)", "Fallan las llamadas personales (401 / 403)"), t("Public access does not grant collection access. Complete OAuth in your client, check the required scopes and refresh or reauthorize an expired session. Do not paste a REST API key into the connector’s OAuth flow.", "El acceso público no concede acceso a la colección. Completa OAuth, comprueba los permisos y renueva o vuelve a autorizar una sesión caducada. No pegues una clave REST en el flujo OAuth del conector.")],
        [t("Invalid parameters or cursor", "Parámetros o cursor inválidos"), t("Use the advertised schema, exact parameter names and valid ranges. Reuse pagination cursors only with the original query. If the dataset changed or a cursor was rejected, restart without it. Replace every <...> example placeholder with a real returned ID.", "Usa el esquema anunciado, nombres exactos y rangos válidos. Reutiliza cursores solo con su consulta original. Si cambia la importación o se rechaza un cursor, reinicia sin él. Sustituye cada <...> por un ID real devuelto.")],
        [t("Rate limit, timeout or unavailable data", "Límite, espera agotada o datos no disponibles"), t("On 429, respect Retry-After when supplied and slow down. Retry transient read errors with backoff, smaller limits or fewer cards. A 503 card_rules_unavailable means the imported dataset is unavailable. For a write timeout, inspect the account before retrying.", "Ante un 429, respeta Retry-After si se incluye y reduce el ritmo. Reintenta errores temporales de lectura con esperas y límites menores. Un 503 card_rules_unavailable indica una importación no disponible. Ante un timeout de escritura, comprueba la cuenta antes de repetir.")],
      ].map(([title, body]) => <details className={styles.expandable} key={title}><summary>{title}</summary><p>{body}</p></details>)}
      <p>{t("When reporting a problem, include the tool name, time, sanitized error and request ID if present. Do not share tokens, personal responses or your entire conversation.", "Al informar de un problema, incluye herramienta, hora, error sin datos sensibles e ID de petición si existe. No compartas tokens, respuestas personales ni toda la conversación.")}</p>
    </GuideSection>
    <GuideSection id="developers" title={t("Build against the live contract", "Integra usando el contrato publicado")}>
      <p>{t("Use an MCP SDK to initialize the connection, negotiate the protocol version, send notifications/initialized and discover tools/list before calling tools/call. The hosted server uses Streamable HTTP and advertises OAuth discovery metadata. A browser page at /mcp is this guide; the actual protocol endpoint is the workers.dev URL above.", "Usa un SDK MCP para inicializar la conexión, negociar versión, enviar notifications/initialized y descubrir tools/list antes de tools/call. El servidor usa Streamable HTTP y anuncia metadatos OAuth. La página /mcp es esta guía; el endpoint del protocolo es la URL workers.dev indicada arriba.")}</p>
      <CopyBlock label={t("JSON-RPC tool call after initialization", "Llamada JSON-RPC tras la inicialización")} text={JSON.stringify({ jsonrpc: "2.0", id: 2, method: "tools/call", params: { name: "get_card_rules", arguments: { card: "Beorn the Fierce" } } }, null, 2)} />
      <p>{t("Validate both protocol errors and tool isError results. Handle content and structuredContent, honor pagination and response-size limits, and retain provenance. A direct REST integration instead uses /api/v1 and its own API-key/scoping rules.", "Valida errores del protocolo y resultados isError. Procesa content y structuredContent, respeta paginación y límites de respuesta y conserva la procedencia. Una integración REST directa utiliza /api/v1 y sus propias reglas de claves y permisos.")}</p>
      <div className={styles.resourceLinks}><Link href="/developers#reference">{t("REST API reference", "Referencia REST API")} ↗</Link><a href="/api/v1/openapi.json">OpenAPI JSON ↗</a><a href="https://magic-brain-mcp.assarasua.workers.dev/healthz">{t("MCP health", "Estado del MCP")} ↗</a><a href="https://github.com/assarasua/magic-brain/blob/main/docs/mcp-tools.md">{t("Repository reference", "Referencia del repositorio")} ↗</a><a href="https://github.com/assarasua/magic-brain/tree/main/integrations/magic-brain-mcp">{t("Source & self-hosting", "Código y alojamiento propio")} ↗</a><a href="https://modelcontextprotocol.io/docs/learn/architecture">{t("MCP architecture", "Arquitectura MCP")} ↗</a></div>
    </GuideSection>
  </GuideShell>;
}
