export const mcpEndpoint = "https://magic-brain-mcp.assarasua.workers.dev/mcp";
export type Bilingual = readonly [string, string];
export type ToolGuide = {
  name: string;
  group: string;
  purpose: Bilingual;
  result: Bilingual;
  example: Record<string, unknown>;
  scopes?: string[];
  writes?: boolean;
};

export const toolGroups: Record<string, Bilingual> = {
  cards: ["Cards & prices", "Cartas y precios"],
  rules: ["Card effects & rules", "Efectos y reglas"],
  research: ["Sets & market research", "Ediciones y mercado"],
  account: ["Your collection", "Tu colección"],
  actions: ["Confirmed account actions", "Acciones confirmadas"],
  product: ["About Magic Brain", "Sobre Magic Brain"],
};

// Examples with <...> placeholders require an identifier returned by a prior read.
// Keep this guide aligned with the server; the contract test checks tool coverage.
export const toolGuides: ToolGuide[] = [
  { name: "search_cards", group: "cards", purpose: ["Find exact printings by card or set name.", "Encuentra impresiones por nombre de carta o edición."], result: ["Printing IDs, set, collector number, language, image and latest prices. Searches names, not Oracle text; punctuation is literal. Use the returned cursor for another page.", "IDs de impresión, edición, número, idioma, imagen y últimos precios. Busca nombres, no texto Oracle; la puntuación es literal. Usa el cursor devuelto para otra página."], example: { query: "Beorn the Fierce", set_code: "hob", limit: 3 } },
  { name: "get_card", group: "cards", purpose: ["Inspect one printing returned by search_cards.", "Consulta una impresión obtenida con search_cards."], result: ["Catalogue metadata and latest prices. For mana cost, Oracle text and rulings, use get_card_rules with the name, Oracle ID or printing ID.", "Metadatos del catálogo y últimos precios. Para maná, texto Oracle y rulings, usa get_card_rules con el nombre, ID Oracle o ID de impresión."], example: { card_id: "<printing-uuid>" } },
  { name: "get_latest_prices", group: "cards", purpose: ["Compare current recorded prices for up to 100 printings.", "Compara los precios registrados de hasta 100 impresiones."], result: ["Available EUR observations with source, finish and observation date. Missing observations are not zero or a live seller quote.", "Observaciones disponibles en EUR con fuente, acabado y fecha. Un dato ausente no equivale a cero ni a una oferta de venta."], example: { card_ids: ["<printing-uuid>"] } },
  { name: "get_price_history", group: "cards", purpose: ["Read a printing’s price observations within a date range.", "Consulta el historial de una impresión entre dos fechas."], result: ["Dated EUR observations for nonfoil, foil or both. Use YYYY-MM-DD dates; the public API bounds the range to 366 days. Gaps remain gaps.", "Observaciones en EUR de acabado normal, foil o ambos. Usa fechas YYYY-MM-DD; la API limita el intervalo a 366 días. Los huecos siguen siendo datos ausentes."], example: { card_id: "<printing-uuid>", start_date: "2026-08-01", end_date: "2026-09-01", finish: "nonfoil" } },
  { name: "get_market_movers", group: "cards", purpose: ["Rank the largest observed price rises or falls.", "Ordena las mayores subidas o bajadas observadas."], result: ["Printing identity, current and comparison prices, absolute and percentage changes. A large change does not establish trading volume or liquidity.", "Impresión, precio actual y anterior, cambio absoluto y porcentual. Un cambio grande no demuestra volumen de ventas ni liquidez."], example: { direction: "gainers", days: 7, limit: 10 } },
  { name: "get_card_rules", group: "rules", purpose: ["Get a card’s Oracle text, mana cost, faces and rulings.", "Obtén texto Oracle, maná, caras y rulings de una carta."], result: ["Complete card faces, verbatim effect paragraphs, source links and dated rulings labelled Wizards or Scryfall. Exact names and IDs only; a full name takes priority over a face match. At most 50 rulings, with explicit truncation. Each source has its own snapshot date.", "Caras completas, párrafos literales de efectos, fuentes y rulings fechados de Wizards o Scryfall. Solo nombres exactos e IDs; el nombre completo tiene prioridad sobre una cara. Hasta 50 rulings, con truncamiento explícito. Cada fuente tiene su propia fecha."], example: { card: "Beorn the Fierce" } },
  { name: "search_card_effects", group: "rules", purpose: ["Discover cards by words in their effects.", "Descubre cartas por las palabras de sus efectos."], result: ["Matching Oracle paragraphs, card names, Oracle IDs and source links. This is English full-text retrieval, not a rules simulator or guaranteed exact-phrase match. Pagination stays tied to one imported dataset.", "Párrafos Oracle coincidentes, nombres, IDs Oracle y fuentes. Es búsqueda textual en inglés, no un simulador ni una garantía de coincidencia literal. La paginación permanece ligada a una misma importación."], example: { query: "draw a card", limit: 5 } },
  { name: "explain_card_interaction", group: "rules", purpose: ["Assemble evidence for an interaction involving 1–5 cards.", "Reúne evidencias para una interacción entre 1 y 5 cartas."], result: ["Per-card found, missing or ambiguous status, Oracle text, dated rulings and candidate Comprehensive Rules citations. The assistant interprets the evidence and your unverified game state; the tool does not execute the game or certify the outcome.", "Estado de cada carta, texto Oracle, rulings y citas candidatas de las Comprehensive Rules. El asistente interpreta las evidencias y el estado de juego aportado, que no se verifica; la herramienta no ejecuta la partida ni certifica el resultado."], example: { cards: ["Rest in Peace", "Blood Artist"], question: "Does Blood Artist trigger if another creature would die?", game_state: { battlefield: ["Rest in Peace, Blood Artist and another creature"], relevant_effects: ["The other creature would be put into its graveyard from the battlefield."] } } },
  { name: "search_rules", group: "rules", purpose: ["Find numbered rules or glossary entries.", "Busca reglas numeradas o entradas del glosario."], result: ["Bounded excerpts with rule numbers, section, PDF page and official URL from a pinned Comprehensive Rules edition. It does not look up a named card’s Oracle text or card rulings.", "Extractos con número de regla, sección, página PDF y URL oficial de una edición fijada de las Comprehensive Rules. No consulta texto Oracle ni rulings de cartas por nombre."], example: { query: "702.19 trample", limit: 5, include_glossary: false } },
  { name: "ask_rules", group: "rules", purpose: ["Retrieve general rules evidence for a question.", "Recupera reglas generales para una pregunta."], result: ["Official excerpts plus a clearly non-authoritative synthesis. Use explain_card_interaction when the answer depends on the actual text of named cards.", "Extractos oficiales y una síntesis explícitamente no autoritativa. Usa explain_card_interaction si la respuesta depende del texto de cartas concretas."], example: { question: "What happens to X when a spell is copied?", limit: 5 } },
  { name: "list_sets", group: "research", purpose: ["Discover set codes and release metadata.", "Descubre códigos de edición y fechas de lanzamiento."], result: ["A paginated set list with name, code, release date and availability metadata. Use these codes in later research calls.", "Lista paginada con nombre, código, fecha y disponibilidad. Usa los códigos devueltos en las siguientes consultas."], example: { query: "Hobbit", tabletop_only: true, limit: 10 } },
  { name: "get_latest_set_opportunities", group: "research", purpose: ["Research signals in the latest or a selected set.", "Investiga señales en la última edición o en una elegida."], result: ["A bounded ranking with source dates, confidence labels and methodology. Confidence describes the research signal; it is not a probability of profit.", "Clasificación acotada con fechas, confianza y metodología. La confianza describe la señal; no es una probabilidad de beneficio."], example: { set_code: "hob", minimum_confidence: 0.5, limit: 5 } },
  { name: "search_opportunity_graph", group: "research", purpose: ["Explore related public card opportunities.", "Explora oportunidades públicas relacionadas."], result: ["A bounded graph of cards and evidence-backed relationships, optionally centered on one printing. It is public research, not a view of your collection.", "Grafo acotado de cartas y relaciones respaldadas por evidencias, opcionalmente centrado en una impresión. Es investigación pública, no una vista de tu colección."], example: { query: "Beorn", limit: 12 } },
  { name: "predict_set_growth", group: "research", purpose: ["Model set growth under explicit assumptions.", "Modela la evolución de una edición con supuestos explícitos."], result: ["Observation date, evidence coverage, normalized assumptions, forecast range and methodology. Benchmarks are illustrative; this is an unsaved scenario and no trade is placed.", "Fecha, cobertura, supuestos normalizados, intervalo previsto y metodología. Las referencias son ilustrativas; el escenario no se guarda ni ejecuta operaciones."], example: { set_code: "hob", target: "sp500", horizon_months: 24, demand: 3, scarcity: 3, reprint_resilience: 3 } },
  { name: "build_portfolio_scenario", group: "research", purpose: ["Build a hypothetical collection allocation from public data.", "Construye una asignación hipotética con datos públicos."], result: ["Suggested positions, quantities, weights, unused budget and rationale. This neither reads nor changes your actual holdings. Seller inventory, fees and execution prices are not checked.", "Posiciones, cantidades, pesos, presupuesto libre y explicación. No consulta ni cambia tus cartas reales. No comprueba inventario de vendedores, comisiones ni precios de ejecución."], example: { set_code: "hob", budget_eur: 100, risk: "balanced", max_positions: 5 } },
  { name: "get_latest_market_brief", group: "research", purpose: ["Read the newest stored daily market brief.", "Lee el último resumen diario de mercado guardado."], result: ["Publication and market-data dates, recorded movements and source attribution. Briefs summarize stored prices; they are not a live external news feed.", "Fechas de publicación y datos, movimientos y fuentes. Los resúmenes sintetizan precios guardados; no son noticias externas en directo."], example: {} },
  { name: "list_market_briefs", group: "research", purpose: ["Browse the daily market brief archive.", "Consulta el archivo de resúmenes diarios."], result: ["A bounded archive in reverse chronological order. Choose a returned date for get_market_brief_by_date.", "Archivo acotado de más reciente a más antiguo. Elige una fecha devuelta para get_market_brief_by_date."], example: { limit: 7 } },
  { name: "get_market_brief_by_date", group: "research", purpose: ["Retrieve the saved brief for a particular day.", "Recupera el resumen guardado de un día concreto."], result: ["The immutable brief for a YYYY-MM-DD date, or not found when that date has no publication.", "Resumen inmutable de una fecha YYYY-MM-DD, o no encontrado si ese día no tiene publicación."], example: { date: "2026-09-19" } },
  { name: "get_personalized_opportunities", group: "account", scopes: ["profile:read"], purpose: ["Research cards using your saved preferences.", "Investiga cartas según tus preferencias guardadas."], result: ["Owner-specific opportunity research with preference context and source evidence. Authorize profile access first.", "Investigación personalizada con contexto de preferencias y fuentes. Autoriza antes el acceso al perfil."], example: { limit: 5 } },
  { name: "get_predict_recommendation", group: "account", scopes: ["profile:read"], purpose: ["Read a recommendation based on your saved profile.", "Consulta una recomendación según tu perfil guardado."], result: ["A personal research recommendation with its methodology and limitations. It does not buy cards or edit preferences.", "Recomendación personal con metodología y limitaciones. No compra cartas ni modifica preferencias."], example: {} },
  { name: "get_portfolio_intelligence", group: "account", scopes: ["portfolio:read", "profile:read"], purpose: ["Understand your collection’s value and concentration.", "Comprende el valor y la concentración de tu colección."], result: ["Owned holdings summary, unrealized change, contributors, concentration and 1/3/5-year projections. Preserve the model or fallback status and missing-data notices.", "Resumen de cartas propias, variación no realizada, contribuciones, concentración y proyecciones a 1/3/5 años. Conserva el estado del modelo o alternativa y los avisos de datos ausentes."], example: {} },
  { name: "list_portfolio_lists", group: "account", scopes: ["lists:read"], purpose: ["Find your collection lists and their IDs.", "Encuentra tus listas de colección y sus IDs."], result: ["Owned lists and holding counts. These list IDs can be used for subsequent reads or confirmed actions.", "Listas propias y recuentos. Sus IDs sirven para posteriores consultas o acciones confirmadas."], example: {} },
  { name: "get_portfolio_list", group: "account", scopes: ["lists:read", "portfolio:read", "profile:read"], purpose: ["Inspect one of your collection lists.", "Consulta una de tus listas de colección."], result: ["Owned list holdings, valuation, concentration and projections. A list ID does not grant access to another person’s collection.", "Cartas, valoración, concentración y proyecciones de una lista propia. Un ID no permite acceder a la colección de otra persona."], example: { list_id: "<owned-list-uuid>" } },
  { name: "add_to_portfolio", group: "actions", writes: true, scopes: ["portfolio:write"], purpose: ["Add a confirmed holding to your collection.", "Añade una carta confirmada a tu colección."], result: ["Adds to the default or specified owned list. Confirm printing, quantity, recorded purchase price, condition and language first. This records ownership; it does not purchase a card.", "Añade a la lista predeterminada o a una lista propia indicada. Confirma antes impresión, cantidad, precio de compra registrado, estado e idioma. Registra propiedad; no compra la carta."], example: { card_id: "<printing-uuid>", quantity: 1, purchase_price: 2.5, condition: "near_mint", language: "en", confirm: true } },
  { name: "add_to_watchlist", group: "actions", writes: true, scopes: ["alerts:manage"], purpose: ["Add or update a watched printing and its alerts.", "Añade o actualiza una impresión en seguimiento y sus alertas."], result: ["Updates your watchlist and optional above/below price thresholds. Confirm the printing, thresholds and enabled flags before sending.", "Actualiza el seguimiento y los umbrales de precio opcionales. Confirma impresión, umbrales y activación antes de enviar."], example: { card_id: "<printing-uuid>", target_price: 2, alert_below_enabled: true, confirm: true } },
  { name: "remove_from_watchlist", group: "actions", writes: true, scopes: ["alerts:manage"], purpose: ["Remove a confirmed watched printing.", "Elimina una impresión confirmada del seguimiento."], result: ["Removes that card from your watchlist. It does not remove owned holdings.", "Elimina esa carta del seguimiento. No elimina cartas de tu colección."], example: { card_id: "<printing-uuid>", confirm: true } },
  { name: "create_portfolio_list", group: "actions", writes: true, scopes: ["lists:write"], purpose: ["Create a named collection list.", "Crea una lista de colección con nombre."], result: ["Creates an owned list and returns its identity. Show the proposed name to the user before confirming.", "Crea una lista propia y devuelve su identidad. Muestra el nombre propuesto antes de confirmar."], example: { name: "Bears", confirm: true } },
  { name: "rename_portfolio_list", group: "actions", writes: true, scopes: ["lists:write"], purpose: ["Rename an existing owned list.", "Cambia el nombre de una lista propia."], result: ["Updates the selected list name. Read your lists first to distinguish similarly named collections.", "Actualiza el nombre de la lista elegida. Consulta antes tus listas para distinguir nombres similares."], example: { list_id: "<owned-list-uuid>", name: "Bears deck", confirm: true } },
  { name: "remove_portfolio_holdings", group: "actions", writes: true, scopes: ["portfolio:write", "lists:write"], purpose: ["Delete confirmed holdings from one owned list.", "Elimina cartas confirmadas de una lista propia."], result: ["Deletes up to 200 holding records, not a requested number of copies. Use integer holding IDs returned by the list and verify the source list and complete removal selection first.", "Elimina hasta 200 registros de cartas, no una cantidad de copias solicitada. Usa los IDs enteros devueltos por la lista y verifica antes la lista de origen y toda la selección."], example: { holding_ids: [123], source_list_id: "<owned-list-uuid>", confirm: true } },
  { name: "search_product_knowledge", group: "product", purpose: ["Find sourced facts and hypotheses about Magic Brain.", "Busca hechos e hipótesis documentados sobre Magic Brain."], result: ["Evidence with source URLs, topic and claim status. Shipped facts, operating principles, hypotheses, roadmap options and unmeasured unknowns stay distinct.", "Evidencias con URL, tema y estado de cada afirmación. Se distinguen hechos publicados, principios, hipótesis, opciones futuras y datos no medidos."], example: { query: "data provenance", limit: 5 } },
  { name: "get_product_context", group: "product", purpose: ["Collect a broader evidence bundle by topic.", "Reúne un conjunto de evidencias por tema."], result: ["Source-cited product context for 1–6 selected topics. Unknown business metrics remain unknown; this is not card gameplay advice.", "Contexto documentado para entre 1 y 6 temas. Las métricas desconocidas siguen siendo desconocidas; no es asesoramiento sobre partidas."], example: { topics: ["positioning", "provenance_and_trust"], limit: 8 } },
  { name: "ask_product_question", group: "product", purpose: ["Ground a question about Magic Brain in documented evidence.", "Fundamenta una pregunta sobre Magic Brain con evidencias."], result: ["Relevant statements and answer instructions for the host assistant. Claims need their cited source and status; missing metrics must not be invented.", "Afirmaciones relevantes e instrucciones para el asistente. Cada afirmación conserva fuente y estado; no se inventan métricas ausentes."], example: { question: "Where does Magic Brain get its card and price data?", limit: 5 } },
];
