"use client";

import Link from "next/link";
import { useState } from "react";
import { useLanguage } from "@/components/language-provider";
import { webMcpDestinations } from "@/lib/web-mcp";
import { instinctInviteUrl } from "@/lib/public-integration-links";
import { CopyBlock, GuideSection, GuideShell } from "./guide-shell";
import { toolGroups, toolGuides } from "./tool-reference";
import { BrowserCompatibility } from "./compatibility";
import styles from "./guides.module.css";

export function WebMcpGuide() {
  const { locale } = useLanguage();
  const es = locale === "es";
  const t = (en: string, spanish: string) => es ? spanish : en;
  const [support, setSupport] = useState<"unknown" | "detected" | "missing">("unknown");
  const publicTools = toolGuides.filter(tool => !tool.scopes);
  const sections = [
    ["start", t("Get started", "Primeros pasos")],
    ["compatibility", t("Browser compatibility", "Navegadores compatibles")],
    ["overview", t("How it works", "Cómo funciona")],
    ["navigation", t("Navigate Magic Brain", "Navega por Magic Brain")],
    ["research", t("Public research tools", "Herramientas públicas")],
    ["examples", t("Examples", "Ejemplos")],
    ["permissions", t("Sessions & permissions", "Sesiones y permisos")],
    ["troubleshooting", t("Browser troubleshooting", "Problemas del navegador")],
    ["integration", t("Integration details", "Detalles de integración")],
  ] as const;
  return <GuideShell kind="webmcp" title={t("Magic Brain, in your browser’s tools.", "Magic Brain, entre las herramientas de tu navegador.")} intro={t("Let a compatible browser agent navigate Magic Brain and retrieve public card, price and rules evidence from the page you have open. Learn what is available, how it connects to the remote MCP, and where browser permissions still apply.", "Permite a un agente compatible navegar por Magic Brain y consultar evidencias públicas de cartas, precios y reglas desde la página abierta. Descubre qué está disponible, cómo se conecta al MCP remoto y qué permisos del navegador siguen aplicándose.")} sections={[...sections]}>
    <GuideSection id="start" title={t("Start in a compatible browser", "Empieza en un navegador compatible")}>
      <div className={styles.recommendation}>
        <span>{t("OUR RECOMMENDATION", "NUESTRA RECOMENDACIÓN")}</span>
        <h3>{t("Try WebMCP with Instinct", "Prueba WebMCP con Instinct")}</h3>
        <p>{t("We recommend Instinct for getting started with a browser agent. Use Asier’s invitation, open Magic Brain in Instinct’s browser, and ask the agent to discover the tools on the page.", "Recomendamos Instinct para empezar con un agente en el navegador. Usa la invitación de Asier, abre Magic Brain en el navegador de Instinct y pide al agente que descubra las herramientas de la página.")}</p>
        <a className={styles.inviteButton} href={instinctInviteUrl}>{t("Join Instinct with Asier’s invitation", "Entrar en Instinct con la invitación de Asier")} ↗</a>
        <ol><li>{t("Open the invitation and follow Instinct’s own access or sign-in steps.", "Abre la invitación y sigue los pasos de acceso de Instinct.")}</li><li>{t("Open https://magicbrain.es/webmcp in Instinct’s browser, keeping the page available to the agent.", "Abre https://magicbrain.es/webmcp en el navegador de Instinct y mantén la página disponible para el agente.")}</li><li>{t("Ask the agent to list the page tools, then use get_card_rules for Beorn the Fierce or navigate_magic_brain to open market_movers.", "Pide al agente que enumere las herramientas de la página y use get_card_rules para Beorn the Fierce o navigate_magic_brain para abrir market_movers.")}</li></ol>
        <p>{t("The invitation opens Instinct; it does not automatically enable WebMCP. Availability depends on the browser/agent environment. Use the check below and the agent’s tool list. If page tools are unavailable, connect the remote MCP instead.", "La invitación abre Instinct; no activa WebMCP automáticamente. La disponibilidad depende del entorno del navegador/agente. Usa la comprobación de abajo y la lista de herramientas del agente. Si no aparecen, conecta el MCP remoto.")} <Link href="/mcp#connect">{t("Remote MCP setup", "Configurar MCP remoto")} →</Link></p>
      </div>
      <h3>{t("In Instinct or another compatible browser", "En Instinct u otro navegador compatible")}</h3>
      <ol className={styles.steps}><li><strong>{t("Open magicbrain.es.", "Abre magicbrain.es.")}</strong> {t("Keep the page open in a browser connected to an agent that supports WebMCP. Magic Brain performs its own registration; your browser or agent may still require setup or permissions.", "Mantén la página abierta en un navegador conectado a un agente compatible con WebMCP. Magic Brain registra sus herramientas, pero tu navegador o agente puede necesitar configuración o permisos.")}</li><li><strong>{t("Let the agent discover page tools.", "Permite que el agente descubra las herramientas.")}</strong> {t("Look for navigate_magic_brain and public tools such as get_card_rules. Navigation registers locally. Research tools appear after remote discovery succeeds, so an internet connection is needed.", "Busca navigate_magic_brain y herramientas públicas como get_card_rules. La navegación se registra localmente; las consultas aparecen tras descubrir el catálogo remoto, por lo que necesitan internet.")}</li><li><strong>{t("Ask for a small read or navigation.", "Pide una consulta o navegación sencilla.")}</strong> {t("Try “Open the Developers page” or “Get Beorn the Fierce’s Oracle text and rulings.” The agent should select the appropriate structured tool and show its result.", "Prueba «Abre la página de Desarrolladores» o «Consulta el Oracle y rulings de Beorn the Fierce». El agente debe seleccionar la herramienta adecuada y mostrar el resultado.")}</li><li><strong>{t("Sign in for private pages.", "Inicia sesión para páginas privadas.")}</strong> {t("Opening your collection uses the website’s ordinary session rules. Public research tools remain anonymous even when the website is signed in.", "Abrir tu colección sigue las reglas normales de sesión de la web. Las consultas públicas siguen siendo anónimas aunque hayas iniciado sesión.")}</li></ol>
      <div className={styles.supportCheck}><div><h3>{t("Can this page see a registration API?", "¿Esta página detecta una API de registro?")}</h3><p>{t("This checks for registerTool only. It cannot confirm your agent’s connection, permissions or successful remote discovery.", "Solo comprueba si existe registerTool. No confirma la conexión del agente, sus permisos ni el éxito del descubrimiento remoto.")}</p></div><button type="button" onClick={() => {
        const doc = document as Document & { modelContext?: { registerTool?: unknown } };
        const nav = navigator as Navigator & { modelContext?: { registerTool?: unknown } };
        const context = doc.modelContext ?? nav.modelContext;
        setSupport(typeof context?.registerTool === "function" ? "detected" : "missing");
      }}>{t("Check this browser", "Comprobar navegador")}</button><p className={styles.supportResult} role="status">{support === "unknown" ? t("Not checked yet.", "Todavía no comprobado.") : support === "detected" ? t("Registration API detected. Check the agent’s tool list next.", "API de registro detectada. Comprueba ahora la lista del agente.") : t("No supported registration API detected on this page. Use the remote MCP, or check your browser agent’s setup.", "No se detecta una API de registro compatible. Usa el MCP remoto o revisa la configuración de tu agente.")}</p></div>
      <p>{t("WebMCP support is still evolving. Magic Brain feature-detects the API instead of assuming support from a browser name or version. In an unsupported environment the normal website remains usable.", "La compatibilidad con WebMCP sigue evolucionando. Magic Brain detecta la API en lugar de asumir compatibilidad por nombre o versión del navegador. La web sigue funcionando en entornos no compatibles.")}</p>
    </GuideSection>
    <GuideSection id="compatibility" title={t("Browser and agent compatibility", "Compatibilidad de navegadores y agentes")}><BrowserCompatibility /></GuideSection>
    <GuideSection id="overview" title={t("Navigation and research, exposed by the page", "Navegación e investigación desde la página")}>
      <p>{t("WebMCP makes structured page tools available to a compatible browser agent. Magic Brain registers a navigation tool locally, then discovers the hosted MCP catalogue and registers its public research tools in the browser. The agent can select a tool and pass named arguments instead of guessing URLs or scraping a result from the screen.", "WebMCP pone herramientas estructuradas de la página a disposición de un agente compatible. Magic Brain registra una herramienta local de navegación, descubre el catálogo del MCP alojado y registra sus herramientas públicas en el navegador. El agente puede elegir una herramienta y aportar parámetros sin adivinar URLs ni extraer resultados de la pantalla.")}</p>
      <div className={styles.stats}><div><strong>1</strong><span>{t("local navigation tool", "herramienta local de navegación")}</span></div><div><strong>{publicTools.length}</strong><span>{t("public tools from the MCP", "herramientas públicas del MCP")}</span></div><div><strong>{t("Preview", "Vista previa")}</strong><span>{t("requires a compatible agent", "requiere un agente compatible")}</span></div></div>
      <div className={styles.tableWrap}><table><thead><tr><th>{t("Connection", "Conexión")}</th><th>WebMCP</th><th>{t("Remote MCP", "MCP remoto")}</th></tr></thead><tbody><tr><td>{t("Where you use it", "Dónde se usa")}</td><td>{t("An open Magic Brain page in a compatible browser", "Una página de Magic Brain abierta en un navegador compatible")}</td><td>{t("An external MCP client or assistant", "Un cliente MCP o asistente externo")}</td></tr><tr><td>{t("Setup", "Configuración")}</td><td>{t("Page registration; your browser/agent must support it", "Registro desde la página; el navegador/agente debe admitirlo")}</td><td>{t("Add the hosted Streamable HTTP endpoint", "Añade el endpoint Streamable HTTP alojado")}</td></tr><tr><td>{t("Public research", "Investigación pública")}</td><td>{t("21 tools bridged to the hosted service", "21 herramientas conectadas al servicio alojado")}</td><td>{t("The same 21 public tools", "Las mismas 21 herramientas públicas")}</td></tr><tr><td>{t("Personal reads and actions", "Consultas y acciones personales")}</td><td>{t("Excluded from this browser bridge", "Excluidas de esta integración del navegador")}</td><td>{t("Available with OAuth scopes and confirmation for writes", "Disponibles con OAuth y confirmación para escritura")}</td></tr><tr><td>{t("Navigation", "Navegación")}</td><td><code>navigate_magic_brain</code></td><td>{t("No browser navigation tool", "Sin herramienta de navegación del navegador")}</td></tr></tbody></table></div>
      <p>{t("If your assistant uses a server URL in its connector settings, follow the ", "Si tu asistente utiliza una URL de servidor en sus ajustes, sigue la ")}<Link href="/mcp">{t("remote MCP guide", "guía del MCP remoto")}</Link>{t(". /webmcp is documentation, not a protocol endpoint.", ". /webmcp es documentación, no un endpoint del protocolo.")}</p>
    </GuideSection>
    <GuideSection id="navigation" title="navigate_magic_brain">
      <p>{t("Pass one required destination string from the allowlist below. The tool changes the current page through the application router and returns the accepted destination and path. It does not accept arbitrary URLs, create holdings, submit forms or purchase cards.", "Pasa un parámetro destination de la lista permitida. La herramienta cambia de página mediante la navegación de la aplicación y devuelve destino y ruta aceptados. No acepta URLs arbitrarias, crea cartas, envía formularios ni compra cartas.")}</p>
      <CopyBlock label={t("Input", "Entrada")} text={'{\n  "destination": "developers"\n}'} /><CopyBlock label={t("Structured result", "Resultado estructurado")} text={'{\n  "destination": "developers",\n  "path": "/developers"\n}'} />
      <div className={styles.tableWrap}><table><thead><tr><th>destination</th><th>{t("Page", "Página")}</th><th>{t("Route", "Ruta")}</th></tr></thead><tbody>{webMcpDestinations.map((item) => <tr key={item.id}><td><code>{item.id}</code></td><td>{({ overview: t("Overview", "Resumen"), market: t("Market", "Mercado"), market_movers: t("Public market movers", "Movimientos públicos"), "latest-set-watch": t("Latest set watch", "Última edición"), portfolio: t("Collection", "Colección"), inventory: t("Inventory", "Inventario"), discover: t("Discover", "Descubrir"), watchlist: t("Watchlist", "Seguimiento"), "reserved-list": "Reserved List", brain: "Brain", signals: t("Signals", "Señales"), analyst: t("Analyst", "Analista"), predict: t("Predict", "Predecir"), settings: t("Settings", "Ajustes"), developers: t("Developers", "Desarrolladores") })[item.id]}</td><td><code>{item.path}</code></td></tr>)}</tbody></table></div>
      <p>{t("Navigation success confirms a destination was accepted, not that a private page has authorized you or finished loading its data. A signed-out visit to a private area follows the normal sign-in flow. Unknown destinations return a tool error and do not navigate.", "El éxito confirma que el destino se aceptó, no que una página privada te haya autorizado o terminado de cargar. Si no has iniciado sesión, se aplica el acceso normal. Un destino desconocido devuelve un error y no navega.")}</p>
    </GuideSection>
    <GuideSection id="research" title={t("The public MCP catalogue, inside the page", "El catálogo público MCP, dentro de la página")}>
      <p>{t("Magic Brain fetches tools/list from the hosted MCP, removes the account-only tools and registers the remaining tools with their names, descriptions and input/output schemas. Calls are forwarded to the same hosted service. The page does not build a separate rules database, run a second model or make public data available offline.", "Magic Brain consulta tools/list del MCP alojado, excluye las herramientas personales y registra el resto con nombres, descripciones y esquemas. Las llamadas se envían al mismo servicio. La página no crea otra base de reglas, ejecuta otro modelo ni permite consultar datos públicos sin conexión.")}</p>
      {Object.entries(toolGroups).filter(([group]) => publicTools.some(tool => tool.group === group)).map(([group, labels]) => <div className={styles.publicGroup} key={group}><h3>{labels[es ? 1 : 0]}</h3><ul>{publicTools.filter(tool => tool.group === group).map(tool => <li key={tool.name}><Link href={`/mcp#${tool.name}`}><code>{tool.name}</code></Link><span>{tool.purpose[es ? 1 : 0]}</span></li>)}</ul></div>)}
      <p>{t("Use the ", "Consulta la ")}<Link href="/mcp#tools">{t("full MCP reference", "referencia MCP completa")}</Link>{t(" for each tool’s arguments, examples, output fields and limitations. The browser bridge preserves those contracts. The current snapshot has 21 public tools; future server changes can alter the discovered catalogue.", " para ver argumentos, ejemplos, resultados y limitaciones. La integración del navegador conserva esos contratos. El catálogo actual tiene 21 herramientas públicas; cambios futuros del servidor pueden modificarlo.")}</p>
    </GuideSection>
    <GuideSection id="examples" title={t("A few useful browser requests", "Peticiones útiles en el navegador")}>
      <CopyBlock label={t("Navigate", "Navegar")} text={t("Use navigate_magic_brain to open the public market movers page.", "Usa navigate_magic_brain para abrir la página pública de movimientos del mercado.")} />
      <p><code>{'{ "destination": "market_movers" }'}</code></p>
      <CopyBlock label={t("Look up card text", "Consultar una carta")} text={t("Use get_card_rules for Beorn the Fierce. Show the mana cost, complete Oracle text and dated card rulings. Keep source dates visible.", "Usa get_card_rules para Beorn the Fierce. Muestra maná, texto Oracle completo y rulings fechados. Conserva las fechas de las fuentes.")} />
      <CopyBlock label={t("Explain an interaction", "Explicar una interacción")} text={t("Rest in Peace and Blood Artist are on the battlefield. Another creature would die. Use explain_card_interaction, cite the relevant rules, and tell me what additional facts could change the answer.", "Rest in Peace y Blood Artist están en el campo de batalla. Otra criatura fuera a morir. Usa explain_card_interaction, cita las reglas relevantes e indica qué datos adicionales podrían cambiar la respuesta.")} />
      <p>{t("Give the same game-state detail you would provide through remote MCP. Oracle identities and printing IDs are different, card names are exact, and generic search_rules does not retrieve a named card’s Oracle text. See the ", "Aporta el mismo detalle de la situación que en MCP remoto. Identidades Oracle e IDs de impresión son distintos, los nombres de cartas son exactos y search_rules no obtiene Oracle por nombre. Consulta el ")}<Link href="/mcp#card-rules">{t("card-rules walkthrough", "ejemplo de reglas de cartas")}</Link>.</p>
    </GuideSection>
    <GuideSection id="permissions" title={t("What the browser bridge can access", "A qué puede acceder esta integración")}>
      <ul><li>{t("Public research calls are anonymous. The bridge does not forward your website session as OAuth credentials to the hosted MCP.", "Las consultas públicas son anónimas. La integración no reenvía tu sesión web como credenciales OAuth al MCP alojado.")}</li><li>{t("Personalized opportunities, personal predictions, collection analysis, list reads and all six account mutation tools are excluded. Website sign-in does not add them to this bridge.", "Se excluyen oportunidades y predicciones personales, análisis de colección, lectura de listas y las seis herramientas de escritura. Iniciar sesión en la web no las añade a esta integración.")}</li><li>{t("Navigation can open a private page, but its normal authentication still applies. Opening a page does not authorize an account action.", "La navegación puede abrir una página privada, pero se mantiene su autenticación normal. Abrir una página no autoriza una acción sobre la cuenta.")}</li><li>{t("An agent may also have separate browser-control abilities. Those are governed by that agent’s permissions and are not capabilities granted by these WebMCP tools.", "Un agente puede tener capacidades separadas de control del navegador. Dependen de sus propios permisos; estas herramientas WebMCP no se las conceden.")}</li><li>{t("Research arguments and returned evidence travel to and from the hosted MCP. Avoid putting private notes in public research queries and follow the same request-context privacy rules as remote MCP.", "Los argumentos y evidencias viajan al MCP alojado y desde él. No incluyas notas privadas en consultas públicas y respeta las mismas reglas de privacidad que en MCP remoto.")}</li></ul>
      <p>{t("For authorized collection reads or confirmed changes, connect through ", "Para consultas autorizadas de colección o cambios confirmados, conecta mediante ")}<Link href="/mcp#permissions">{t("remote MCP with OAuth", "MCP remoto con OAuth")}</Link>.</p>
    </GuideSection>
    <GuideSection id="troubleshooting" title={t("If tools are missing or a call fails", "Si faltan herramientas o falla una llamada")}>
      {[
        [t("No WebMCP tools at all", "No hay ninguna herramienta WebMCP"), t("Use the detection check above, then inspect your browser agent’s setup. The page must be open and the agent must expose a supported registration API. A normal browser without that capability will not gain tools simply by opening this guide. Use the remote MCP as an alternative.", "Usa la comprobación anterior y revisa la configuración del agente. La página debe estar abierta y el agente debe exponer una API compatible. Abrir esta guía en un navegador normal no añade por sí solo esa capacidad. Usa MCP remoto como alternativa.")],
        [t("Navigation appears, but research tools do not", "Aparece navegación, pero no consultas"), t("Local registration worked, but remote discovery may not have finished or may have failed. Check connectivity, blocking extensions and access to the hosted MCP. Reload the page after fixing connectivity. A working /healthz alone does not prove tools/list succeeded.", "El registro local funcionó, pero el descubrimiento remoto puede estar pendiente o haber fallado. Comprueba conexión, bloqueadores y acceso al MCP alojado. Recarga tras resolverlo. Que /healthz responda no prueba que tools/list haya funcionado.")],
        [t("My collection tools are missing", "Faltan las herramientas de mi colección"), t("That is expected: account tools are filtered out of this bridge. Sign-in only affects website pages. Use an OAuth-capable remote MCP client for account tools.", "Es lo previsto: las herramientas personales se excluyen. Iniciar sesión solo afecta a las páginas web. Usa un cliente MCP remoto compatible con OAuth para tu cuenta.")],
        [t("The browser result is an error", "La respuesta del navegador es un error"), t("Inspect isError and the returned message. Invalid card names, missing data, rate limits and upstream errors follow the same rules as remote MCP. Navigation errors usually mean destination is not in the allowlist. Keep a request ID when one is returned.", "Revisa isError y el mensaje. Nombres inválidos, datos ausentes, límites y errores siguen las reglas del MCP remoto. Un error de navegación suele indicar un destino fuera de la lista. Conserva el ID de petición si se devuelve.")],
        [t("It works on magicbrain.es but not my local copy", "Funciona en magicbrain.es pero no en mi copia local"), t("The hosted service enforces browser-origin rules. A different origin or localhost port may be rejected. Configure origins deliberately for your own deployment, or mock read-only discovery in isolated UI tests. Do not disable browser security.", "El servicio alojado aplica reglas de origen. Otro dominio o puerto local puede rechazarse. Configura orígenes explícitos en tu despliegue o simula el descubrimiento en pruebas aisladas. No desactives la seguridad del navegador.")],
      ].map(([title, body]) => <details key={title} className={styles.expandable}><summary>{title}</summary><p>{body}</p></details>)}
    </GuideSection>
    <GuideSection id="integration" title={t("How Magic Brain registers the tools", "Cómo registra Magic Brain las herramientas")}>
      <p>{t("The page checks document.modelContext first, then navigator.modelContext, and proceeds only when the selected context exposes registerTool. Tool definitions include a name, description, input schema, output schema and execution callback. Registration is cleaned up with unregisterTool when the context supports it.", "La página comprueba primero document.modelContext y después navigator.modelContext; continúa si el contexto elegido expone registerTool. Cada definición incluye nombre, descripción, esquemas y función de ejecución. Cuando el contexto lo permite, unregisterTool limpia el registro.")}</p>
      <p>{t("Navigation resolves a fixed destination through the application’s own route map. Public tool execution sends tools/call to the hosted MCP and returns its text/structured result. It handles JSON and SSE-framed JSON-RPC responses. Registration alone does not prove a tool call will succeed.", "La navegación resuelve un destino fijo mediante el mapa de rutas de la aplicación. Las consultas públicas envían tools/call al MCP alojado y devuelven texto y resultado estructurado. Se admiten respuestas JSON y JSON-RPC encapsulado en SSE. Registrar una herramienta no prueba que su ejecución vaya a funcionar.")}</p>
      <p>{t("For integrations, discover capabilities rather than assuming that browser automation, WebMCP and remote MCP are interchangeable. Treat the published tool schema as the contract and preserve source citations when presenting research results.", "En una integración, descubre las capacidades en lugar de asumir que automatización del navegador, WebMCP y MCP remoto son intercambiables. Usa el esquema publicado como contrato y conserva las fuentes al presentar resultados.")}</p>
      <div className={styles.resourceLinks}><Link href="/mcp#tools">{t("MCP tool reference", "Referencia de herramientas MCP")} ↗</Link><Link href="/developers">{t("Developer hub", "Desarrolladores")} ↗</Link><a href="https://github.com/assarasua/magic-brain/blob/main/src/components/web-mcp-navigation.tsx">{t("Registration source", "Código de registro")} ↗</a><Link href="/privacy">{t("Privacy policy", "Privacidad")} ↗</Link></div>
    </GuideSection>
  </GuideShell>;
}
