import { LegalPage } from "@/components/legal-page";

export default function PrivacyPage() {
  return <LegalPage title={{ en: "Privacy Policy", es: "Política de privacidad" }} intro={{ en: "How Magic Brain uses and protects personal data under the GDPR.", es: "Cómo Magic Brain utiliza y protege los datos personales conforme al RGPD." }} sections={{
    en: [
      { title: "Who is responsible", body: <p>Magic Brain is operated by Asier Sarasua under BizkardoLab, Spain. Contact: <a href="mailto:assarasua@gmail.com">assarasua@gmail.com</a>.</p> },
      { title: "Data we process", body: <><p>We process your Google account identifier, verified email, display name and avatar; collection, watchlist, preferences, referrals and product activity; API keys and OAuth connection metadata; support messages; and payment records when applicable. We do not receive your Google password.</p><p>MCP audit records contain tool name, status, timing and a privacy-minimised request summary. They are not intended to contain full prompts, credentials, card notes or OAuth tokens.</p></> },
      { title: "Why and legal basis", body: <ul><li>Provide your account, collection, APIs and security: performance of our contract.</li><li>Prevent abuse, secure the service and keep minimal operational logs: legitimate interests and legal obligations.</li><li>Send the daily newsletter: consent, which you may withdraw at any time.</li><li>Process payments and accounting records: contract and legal obligations.</li></ul> },
      { title: "Providers and international transfers", body: <p>We use Google for sign-in, Cloudflare for delivery and hosting, Railway/PostgreSQL for application data, Resend for opted-in email, Stripe for payments, and Scryfall/MTGJSON for card data. Some providers may process data outside the EEA using adequacy decisions or contractual safeguards. Their own privacy terms also apply.</p> },
      { title: "Retention", body: <p>Account and collection data remain while your account is active and are deleted when you delete it, except records we must keep by law. Newsletter data remains until you unsubscribe. Security and MCP operational records are retained only as long as reasonably needed for reliability, abuse prevention and dispute handling. Backups may take a limited additional period to expire.</p> },
      { title: "Your rights", body: <p>You may access, correct, export or delete your data, restrict or object to processing, withdraw consent, and lodge a complaint with the Spanish Data Protection Agency (AEPD) or your local authority. Export and deletion are available in Settings; you can also contact us.</p> },
      { title: "Automated insights", body: <p>Magic Brain may rank or recommend cards from collection preferences and market signals. These are informational suggestions, not decisions with legal or similarly significant effects and not financial advice.</p> },
    ],
    es: [
      { title: "Responsable", body: <p>Magic Brain está operado por Asier Sarasua bajo BizkardoLab, España. Contacto: <a href="mailto:assarasua@gmail.com">assarasua@gmail.com</a>.</p> },
      { title: "Datos que tratamos", body: <><p>Tratamos el identificador de tu cuenta de Google, email verificado, nombre y avatar; colección, seguimiento, preferencias, referidos y actividad del producto; claves API y metadatos de conexiones OAuth; mensajes de soporte; y datos de pago cuando corresponda. No recibimos tu contraseña de Google.</p><p>Los registros MCP contienen herramienta, estado, tiempos y un resumen minimizado de la solicitud. No están diseñados para guardar prompts completos, credenciales, notas de cartas ni tokens OAuth.</p></> },
      { title: "Finalidad y base jurídica", body: <ul><li>Prestar la cuenta, colección, APIs y seguridad: ejecución del contrato.</li><li>Evitar abusos, proteger el servicio y mantener registros mínimos: interés legítimo y obligaciones legales.</li><li>Enviar el boletín diario: consentimiento, revocable en cualquier momento.</li><li>Procesar pagos y contabilidad: contrato y obligaciones legales.</li></ul> },
      { title: "Proveedores y transferencias", body: <p>Usamos Google para el acceso, Cloudflare para entrega y alojamiento, Railway/PostgreSQL para datos, Resend para email consentido, Stripe para pagos y Scryfall/MTGJSON para datos de cartas. Algunos proveedores pueden tratar datos fuera del EEE mediante decisiones de adecuación o garantías contractuales.</p> },
      { title: "Conservación", body: <p>Los datos de cuenta y colección se conservan mientras la cuenta esté activa y se eliminan al borrar la cuenta, salvo obligación legal. Los datos del boletín permanecen hasta la baja. Los registros operativos y MCP se conservan solo el tiempo razonablemente necesario para fiabilidad, prevención de abusos y disputas. Las copias de seguridad pueden tardar un periodo adicional limitado en expirar.</p> },
      { title: "Tus derechos", body: <p>Puedes acceder, rectificar, exportar o borrar tus datos, limitar u oponerte al tratamiento, retirar el consentimiento y reclamar ante la AEPD o tu autoridad local. La exportación y borrado están disponibles en Ajustes; también puedes contactarnos.</p> },
      { title: "Recomendaciones automáticas", body: <p>Magic Brain puede ordenar o recomendar cartas usando preferencias y señales de mercado. Son sugerencias informativas, no decisiones con efectos jurídicos o similares, ni asesoramiento financiero.</p> },
    ],
  }} />;
}
